export const WEATHER_LOADING = 'WEATHER_LOADING';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';
export const WEATHER_ERROR = 'WEATHER_ERROR';
export const REFRESH_LOADING = 'REFRESH_LOADING';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_ERROR = 'REFRESH_ERROR';
export const CONVERT_TEMPERATURE = 'CONVERT_TEMPERATURE';
export const CHART_DATA_SUCCESS = 'CHART_DATA_SUCCESS';
